### PR TITLE
Ensure heartbeats are never processed by log consistency algorithm

### LINKED ISSUE #98: `client_read` and `client_write` should share a Mutex lock
When using `client_read` and `client_write`  without Mutex lock, unexpected issues would appear. It takes me a very long time to realize the issue. May I suggest to include a Mutex lock inside these two functions? Alternatively, the document should emphasize the application need to ensure there is no concurrent  `client_read` and `client_write`.

### PR DESCRIPTION
**Pull request by thedodd**
closes #98

### CODE REVIEW

File: async-raft/src/replication/mod.rs [hunk 1]
```diff
@@ -767,7 +777,6 @@ impl<'a, D: AppData, R: AppDataResponse, N: RaftNetwork<D>, S: RaftStorage<D, R>
     #[tracing::instrument(level = "trace", skip(self, snapshot))]
     async fn stream_snapshot(&mut self, mut snapshot: CurrentSnapshotData<S::Snapshot>) -> RaftResult<()> {
         let mut offset = 0;
-        self.core.last_log_index = snapshot.index;
```
Comment (thedodd) [inline async-raft/src/replication/mod.rs:770]: @xu-cheng this was the core of the issue over in #98. This value should not have been updated here, not sure why I was doing so. `self.core.last_log_index` has nothing to do with a peer node's state, it only indicates that last log index to be appended to the local log by the leader (these replication streams only exist when the node is the leader).

This had the potential to cause a mismatch of data during replication, typically right after or during the process of streaming a snapshot to a follower node.

**Comment by xu-cheng** [comment]
Thanks for the fix.
